config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'login#welcome'
  
  #devise_for :users, controllers: {registrations: 'registrations'}
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations'}


  resources :posts do
  	collection do
  		get :wear
  		get :eat
  		get :live
  		get :culture
  	end
  end

  post 'posts/wear'
  post 'posts/eat'
  post 'posts/live'
  post 'posts/culture'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/archive.rb
class Archive < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/book.rb
class Book < ActiveRecord::Base
	searchkick
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  #has_many :archives
  has_many :archiving_users, :through => :archives, class_name:"User"
  enum category: [ :wear, :eat, :live, :culture]
  enum season: [:spring, :summer, :autumn, :winter]

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  before_save :default_values
  has_many :posts
  has_many :archives
  has_many :archived_posts, :through => :archives, class_name:"Post"
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
   def default_values
   	self.is_editor ||=0
   end

   def self.find_for_facebook_oauth(auth)
     user = where(provider: auth[:provider], uid: auth[:uid]).first_or_create do |user|
       user.provider = auth.provider
       user.uid = auth.uid
       user.email = auth.info.email
       user.password = Devise.friendly_token[0,20]
       user.name = auth.info.name   # assuming the user model has a name
       user.image = auth.info.image # assuming the user model has an image
     end

     # 이 때는 이상하게도 after_create 콜백이 호출되지 않아서 아래와 같은 조치를 했다.
     #user.add_role :user if user.roles.empty?
     user   # 최종 반환값은 user 객체이어야 한다.
   end

   def self.new_with_session(params, session)
     super.tap do |user|
       if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
         user.email = data["email"] if user.email.blank?
       end
     end
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
	def welcome
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, only:[ :edit, :update, :destroy]
	before_action :set_post, only: [:show, :edit, :update, :destroy]

	def index
		@posts = Post.all
	end

	def 	eat
		@posts = Post.eat
	end

	def live
		@posts = Post.live
	end
	
	def culture
		@posts = Post.culture
	end
	
	def wear
		@posts = Post.wear
	end



	def show
		  respond_to do |format|
		    format.html # show.html.erb
		    format.xml  { render :xml => @post }
		  end
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.user = current_user
		respond_to do |format|
		    if @post.save
		      format.html { redirect_to(@post,
		                    :notice => 'Post was successfully created.') }
		      format.xml  { render :xml => @post,
		                    :status => :created, :location => @post }
		    else
		      format.html { render :action => "new" }
		      format.xml  { render :xml => @post.errors,
		                    :status => :unprocessable_entity }
		    end
		  end
		end

	def edit
	end

	def update
		if @post.update(post_params)
				redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :content, :category, :image, :season)
	end

	def set_post
		@post = Post.find(params[:id])
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">letter</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "로그아웃", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "로그인", new_user_session_path %></li>
          
        <% end %>
      </ul>

       <!-- <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= image_tag(current_user.image, size: '20x20', style:'border-radius:3px;vertical-align:top;') if current_user.image %>
              <%= current_user.name %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Profile", edit_user_registration_path %></li>
              
            </ul>
          </li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" } %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign in
             <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "with Auth Blog", new_user_session_path %></li>
              <li><%= link_to "with Facebook", user_facebook_omniauth_authorize_path(:facebook) %></li>
            </ul>
          </li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>
      </ul>

      <% if user_signed_in? %>
        <p><%= link_to "로그아웃", destroy_user_session_path, method: :delete, data: {confirm: "Are you sure?" }, class: 'btn btn-default'%></p>
      <% else %>
        <p><%= link_to "로그인", new_user_session_path, class: 'btn btn-default' %></p>
        <p><%= link_to "페이스북으로 로그인", user_facebook_omniauth_authorize_path(:facebook) %></p>
      <% end %>  -->

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Letter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application','style', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div style="text-align:center"><%=link_to image_tag('letter.jpg',style: 'width:20%; padding: 1em 1em;'), root_path %></div>

	<%= render 'layouts/navbar' %>

    <%= yield %>
  </body>
</html>

app/views/layouts/lightbox.html.erb
<div id="blueimp-gallery" class="blueimp-gallery">
  <div class="slides"></div>
  <h3 class="title"></h3>
  <a class="prev">‹</a>
  <a class="next">›</a>
  <a class="close">×</a>
  <a class="play-pause"></a>
  <ol class="indicator"></ol>
</div>
<div id="links">
  <a href=="<%= asset_path("portfolio-1") %>" title="Photo 1">
     <%= image_tag("portfolio-1") %>
  <a href="images/photo2.jpg" title="Photo 2">
    <img src="images/thumb_photo2.jpg" alt="Photo 2">
  </a>
  <a href="images/photo3.jpg" title="Photo 3">
    <img src="images/thumb_photo3.jpg" alt="Photo 3">
  </a>
</div>
<!-- 
<div id="links">
    <a href="<%= asset_path("portfolio-1") %>" title="1" data-gallery>
        <%= image_tag("portfolio-1") %>
    </a>
    <a href="<%= asset_path("portfolio-2") %>" title="1" data-gallery>
    </a>
    <a href="<%= asset_path("portfolio-3") %>" title="1" data-gallery>
    </a>
</div> -->

<script>
document.getElementById('links').onclick = function (event) {
  event = event || window.event;
  var target = event.target || event.srcElement,
    link = target.src ? target.parentNode : target,
    options = {index: link, event: event},
    links = this.getElementsByTagName('a');
  blueimp.Gallery(links, options);
};
</script>

app/views/login/welcome.html.erb
<!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
<div id="blueimp-gallery" class="blueimp-gallery">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body next"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Previous
                    </button>
                    <button type="button" class="btn btn-primary next">
                        Next
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="links">
    <a href="<%= asset_path("IMG_0842") %>" title="Gallery" data-gallery>

        <%= image_tag("IMG_0842", style: 'display: block; margin: auto; width: 100%;') %>
    </a>
    <a href="<%= asset_path("IMG_0816.JPG") %>" title="Woods" data-gallery>
    </a>
    <a href="<%= asset_path("IMG_0821.JPG") %>" title="Pinocchio" data-gallery>
    </a>
    <a href="<%= asset_path("IMG_1890.jpg") %>" title="Sea_analog" data-gallery>
    </a>
    <a href="<%= asset_path("IMG_0026.JPG") %>" title="Bubbles" data-gallery>
    </a>
    <a href="<%= asset_path("IMG_0025.JPG") %>" title="Artist_of_Krakow" data-gallery>
    </a>
    <a href="<%= asset_path("IMG_0039.JPG") %>" title="Budapest" data-gallery>
    </a>
    <a href="<%= asset_path("IMG_0197.JPG") %>" title="Malaga_eye" data-gallery>
    </a>
    <a href="<%= asset_path("IMG_0510.JPG") %>" title="Summer_night" data-gallery>
    </a>
    <a href="<%= asset_path("burano.jpg") %>" title="Burano" data-gallery>
    </a>
</div>

<!-- <div style="text-align:center"><h1><strong> LETTER </strong></h1></div> -->
	<%#= stylesheet_link_tag 'stylish-portfolio' %>
	<%#= stylesheet_link_tag 'bootstrap' %>
	<%#= stylesheet_link_tag 'bootstrap.min' %>

<%#= image_tag('IMG_0842.jpg', style: 'display: block; margin: auto; width: 100%;' ) %>
<br>
<div style="text-align:center"> 
<%=link_to image_tag('IMG_1799.jpg',style: 'text_align:left; width:49%;'), posts_wear_path%>
<%=link_to image_tag('IMG_0813.JPG',style: 'text_align:right; width:49%;'), posts_eat_path%>
<br/>
<br>
<%=link_to image_tag('IMG_0826.JPG',style: 'text_align:left; width:49%;'), posts_live_path%>
<%=link_to image_tag('IMG_1797.JPG',style: 'text_align:right; width:49%;'), posts_culture_path%>
</br>
	<!-- <a href="/posts/wear" class="btn-lg btn-danger" role="button">의</a>
	<a href="/posts/eat" class="btn-lg btn-warning" role="button">식</a><br/><br/>
	<a href="/posts/live" class="btn-lg btn-success" role="button">주</a>
	<a href="/posts/culture" class="btn-lg btn-primary" role="button">락</a> -->
<!-- </div>
<br>
<section id="portfolio" class="portfolio">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1 text-center">

			<hr class="small">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="portfolio-item">
                                <a href="/posts/wear">
                                    <%=link_to image_tag('IMG_1799.JPG',style: 'text_align:left; width:49%;'), posts_wear_path%>
                                </a>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="portfolio-item">
                                <%=link_to image_tag('IMG_0813.JPG',style: 'text_align:right; width:49%;'), posts_eat_path%>
                                </a>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="portfolio-item">
                                <%=link_to image_tag('IMG_0826.JPG',style: 'text_align:left; width:49%;'), posts_live_path%>
                                </a>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="portfolio-item">
                                <%=link_to image_tag('IMG_1797.JPG',style: 'text_align:right; width:49%;'), posts_culture_path%>
                                </a>
                            </div>
                        </div>
                    </div>-->
<br>
<% if user_signed_in?%>
	<% if current_user.is_editor %>

		<div style="text-align:right" class="btn-lg-group">
		<a href="/posts/new" class="btn btn-info" role="button">새 글</a>
		<a href="/posts" class="btn btn-info" role="button">최신글</a>
		</div>
	<% else%> 
		<div style="text-align:right">
		<a href="/posts" class="btn btn-info" role="button">최신글</a>
		</div>
	<% end %>
<% else %>
	<div style="text-align:right">
		<a href="/posts" class="btn btn-info" role="button">최신글</a>
		</div>
<% end %>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %> <br />
	<%= f.input :image, as: :file %>
	<%= f.label :content %>
		<%= f.input :season, collection: Post.seasons.keys, input_html: { :style => 'width: 100px'}%>
		<%= f.input :category, collection: Post.categories.keys, input_html: { :style => 'width: 100px'} %>
  		<%= f.cktext_area :content, class: 'someclass', ckeditor: {uiColor: '#ffecb3', language: 'en'}%>
  <%#= form.cktext_area :content, value: 'Default value', id: 'sometext'%>
  <%#= cktext_area :content, :info, cols: 40, ckeditor: { uiColor: '#AADC6E', toolbar: 'mini' }%>
  		<%= f.submit class: "btn btn-default" %>
<% end %>

app/views/posts/_index.html.erb
<!-- <h1>글 목록</h1>
 -->
<table class="table table-striped">
	<thead>
		<tr>
			<!-- <th>제목</th>
			<th>편집</th>
			<th>자세히보기</th> -->
		</tr>
	</thead>
	<tbody>
		<% @posts.each do |post| %>
				<tr>

						<!-- <td style="background-image: <%= asset_url('a') %>; background-color: #FF00FF;"><%= post.title %></td> -->
						<td><%=link_to post.title, post %></td>
						<!-- <td><%=link_to "편집", edit_post_path(post) %></td>
						<td><%= link_to "자세히 보기", post %></td>
						<td><%= link_to "delete", post_path(post), method: :delete, data: {confirm: 'Are you sure?'} %></td>-->
 				</tr>
		<% end %>
	</tbody>
</table>
<br>
<% if user_signed_in? %>
	<% if current_user.is_editor %>
	<div style="text-align:right">
	<a href="/posts/new" class="btn btn-info" role="button">새 글</a>
	<%end%>
<%end%>

app/views/posts/culture.html.erb
<h3 style="text-align:center"><strong> 락 </strong></h3>
<%= render 'posts/index' %>

app/views/posts/eat.html.erb
<h3 style="text-align:center"><strong> 식 </strong></h3>
<%= render 'posts/index' %>

app/views/posts/edit.html.erb
<h1>편집하기</h1>
 
<%= render 'form' %>
 
<%= link_to '글 보기', @post %> |
<%= link_to '목록', posts_path %>

app/views/posts/index.html.erb
<h3 style="text-align:center"><strong> 전체 글 보기 </strong></h3>
<%=render "posts/index"%>

<!-- <h1>글 목록</h1>

<table class="table table-striped">
	<thead>
		<tr>
			<th>제목</th>
			<th>편집</th>
			<th>자세히보기</th>
		</tr>
	</thead>
	<tbody>
		<% @posts.each do |post| %>
				<tr>

						<td style="background-image: <%= asset_url('a') %>; background-color: #FF00FF;"><%= post.title %></td>
						<td><%=link_to post.title, post %></td>
						<td><%=link_to "편집", edit_post_path(post) %></td>
						<td><%= link_to "자세히 보기", post %></td>
						<td><%= link_to "delete", post_path(post), method: :delete, data: {confirm: 'Are you sure?'} %></td>
 				</tr>
		<% end %>
	</tbody>
</table>
<br>
<a href="/posts/new" class="btn btn-info" role="button">New</a> -->

app/views/posts/live.html.erb
<h3 style="text-align:center"><strong> 주 </strong></h3>
<%= render 'posts/index' %>

app/views/posts/new.html.erb
<h3>새 글 작성하기</h3>
<%= render 'posts/form' %>
<%= link_to "돌아가기", posts_path, class: "btn btn-default" %>

app/views/posts/show.html.erb
  <h3 style = "text-align:center"><%= @post.title %></h3>
  <h5 style = "text-align:right"><%= @post.created_at %></h5>
</p>
<p><%= @post.content.html_safe %></p>
<% if user_signed_in? && current_user.is_editor%>
		<div style = "text-align:right"> <%= link_to '편집', edit_post_path(@post) %> |
			<% if @post.category == 'wear' %>
				<%= link_to "목록", wear_posts_path %>
			<% elsif @post.category == 'eat' %>
				<%= link_to "목록", eat_posts_path %> 
			<% elsif @post.category == 'culture' %>
				<%= link_to "목록", culture_posts_path %> 
			<% elsif @post.category == 'live' %>
				<%= link_to "목록", live_posts_path %>
			<%end%>
			|<%= link_to '삭제', @post, :confirm => 'Are you sure?', :method => :delete %>
		</div>
<% else %> <div style = "text-align:right"> 
		<% if @post.category == 'wear' %>
			<%= link_to "목록", wear_posts_path %> 
		<% elsif @post.category == 'eat' %>
			<%= link_to "목록", eat_posts_path %> 
		<% elsif @post.category == 'culture' %>
			<%= link_to "목록", culture_posts_path %> 
		<% elsif @post.category == 'live' %>
			<%= link_to "목록", live_posts_path %> 	
		<%end%> 
		</div>
<%end%>

app/views/posts/wear.html.erb
<h3 style="text-align:center"><strong> 의 </strong></h3>
<%= render 'posts/index' %>